language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  # udagram-reverseproxy
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy halzamly/reverseproxy:v1

  # udagram-api-feed 
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed halzamly/udagram-api-feed:v1

  # udagram-api-user 
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user halzamly/udagram-api-user:v1

  # udagram-frontend
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend halzamly/udagram-frontend:v1  


# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push halzamly/reverseproxy:v1
  - docker push halzamly/udagram-api-feed:v1
  - docker push halzamly/udagram-api-user:v1
  - docker push halzamly/udagram-frontend:v1